### ISSUE TITLE
Deploy the EPv0.7.0 Bundler to production

### ISSUE THREAD

**Issue by veljkovranic** [bcnmy/bundler#697]

**Comment by TheDivic** [comment]
Moved this back to the backlog because of missing context.

Please use the: "What?", "Why?", "How?" format for documenting your tickets, use this for reference: https://github.com/bcnmy/bundler/issues/702

**Comment by TheDivic** [comment]
Also I guess this task should be reassigned to @TakGN and you should provide instructions and config parameters in the description @veljkovranic
