### ISSUE TITLE
Integration with Gas Estimation package + testing

### ISSUE THREAD

**Issue by veljkovranic** [bcnmy/bundler#698]
## What?
After this PR gets merged: https://github.com/bcnmy/entry-point-gas-estimations/pull/43
we will be able to integrate this new version of Gas Estimation package in bundler.

## Why?
With the introduction of EntryPoint v0.7 the structure of fields has changed (UserOp is different and there is a new type called PackedUserOp). All of this implies that gas estimations needs to be changed in order to accurately represent how much a transaction is going to cost.

## How?
The integration with the older version of gas estimation package already existed, so making it work with the new version should be relatively easy (only using the new UserOp objects instead of the old one).

To be tested in various cases comparing the gas values used by bundler as well as comparing the results to hardcoded version that is currently present.

**Comment by TheDivic** [comment]
Moved this back to the backlog because of missing context.

Please use the: "What?", "Why?", "How?" format for documenting your tickets, use this for reference: https://github.com/bcnmy/bundler/issues/702
