### ISSUE TITLE
Production bundler config setup for EPv0.7

### ISSUE THREAD

**Issue by veljkovranic** [bcnmy/bundler#699]
## What?
Create and setup new bundler config in production GCP cluster.

## Why?
After the introduction of EntryPoint v0.7, several new fields are added to the configuration file. Those must be present in order for the new bundler version to run.

## How?
Take a value of GCP variable, add new fields populated for Base Sepolia and Mainnet and save the new version in the same GCP variable.

**Comment by TheDivic** [comment]
Moved this back to the backlog because of missing context.

Please use the: "What?", "Why?", "How?" format for documenting your tickets, use this for reference: https://github.com/bcnmy/bundler/issues/702
